server:
  port: 7895
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
  datasource:
    url: jdbc:postgresql://localhost:5432/homeStation
    username: web
    password: web
    driver-class-name: org.postgresql.Driver