spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/homeStation
    username: collector
    password: collector
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

stations-path-active: false
stations-path: stations.txt

stations: http://192.168.0.3, http://192.168.0.4, http://192.168.0.5